[application]

# App (Project) Name
name = "screenpipe-app"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "screenpipe-app"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
