[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH && apt-get install --only-upgrade libc6:$CROSS_DEB_ARCH && apt-get install --assume-yes libxcb1-dev:$CROSS_DEB_ARCH"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH && apt-get install --only-upgrade libc6:$CROSS_DEB_ARCH && apt-get install --assume-yes libxcb1-dev:$CROSS_DEB_ARCH"
]

