[package]
name = "screenpipe-vision"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Cross-platform screen capture
xcap = "0.0.10"

# threadpool
threadpool = "1.8.1"
num_cpus = "1.0"

# Image processing
image = "0.25.0"

# OCR
rusty-tesseract = "1.1.10"

# Dates
chrono = { version = "0.4.31", features = ["serde"] }

# Local Embeddings
candle = { package = "candle-core", version = "0.3.2" }
candle-nn = "0.3.2"
candle-transformers = "0.3.2"
tokenizers = "0.15.0"
lazy_static = "1.4.0"
base64 = "0.21.7"
anyhow = "1.0.86"
byteorder = "1.5.0"
hf-hub = "0.3.2"
rand = "0.8.5"

# Log
log = { workspace = true }


[dev-dependencies]
tempfile = "3.3.0"


[[bin]]
name = "pipe-vision"
path = "src/bin/screenpipe-vision.rs"
